### PR TITLE
Address regression on closing tags inside fenced blocks

### LINKED ISSUE #77: Can't parse header when nested HTML tags found in previous section
### Sample test file: [not_ok.md](https://github.com/RobertDober/earmark_parser/files/7742852/not_ok.md)

`## S2` was parsed as `p` tag instead of `h2` when we have nested tag in separate line:
```
<nav>
   <ul></ul>
</nav>
```

```elixir
iex> {:ok, content} = File.read("not_ok.md")
{:ok,
 "## S1\n\nfoo\n\n```elixir\niex> MyModule.foobar()\n\"<nav>\n  <ul></ul>\n</nav>\"\n```\n\n## S2\n\nbar\n"}
iex> EarmarkParser.as_ast(content)          
{:ok,
 [
   {"h2", [], ["S1"], %{}},
   {"p", [], ["foo"], %{}},
   {"pre", [],
    [
      {"code", [{"class", "elixir"}],
       ["iex> MyModule.foobar()\n\"<nav>\n  <ul></ul>\n</nav>\""], %{}}
    ], %{}},
   {"p", [], ["## S2"], %{}},
   {"p", [], ["bar"], %{}}
 ], []}
```

### Sample test file: [ok.md](https://github.com/RobertDober/earmark_parser/files/7742851/ok.md)

`## S2` was parsed correctly as `h2` when we have nested tag in single line:
```
<nav><ul></ul></nav>
```

```elixir
iex> {:ok, content} = File.read("ok.md")    
{:ok,
 "## S1\n\nfoo\n\n```elixir\niex> MyModule.foobar()\n\"<nav><ul></ul></nav>\"\n```\n\n## S2\n\nbar\n"}
iex> EarmarkParser.as_ast(content)      
{:ok,
 [
   {"h2", [], ["S1"], %{}},
   {"p", [], ["foo"], %{}},
   {"pre", [],
    [
      {"code", [{"class", "elixir"}],
       ["iex> MyModule.foobar()\n\"<nav><ul></ul></nav>\""], %{}}
    ], %{}},
   {"h2", [], ["S2"], %{}},
   {"p", [], ["bar"], %{}}
 ], []}
```

### PR DESCRIPTION
**Pull request by josevalim**
This slightly changes the behaviour of invalid Markdown
where a tag is opened and then a fenced code block that
is never closed is within. The previous behaviour already
different from GitHub. We keep the same AST but not we
return warnings.

Closes #77.

### CODE REVIEW

File: test/acceptance/ast/html/block/annotated_block_test.exs [hunk 1]
```diff
@@ -75,9 +75,9 @@ defmodule Acceptance.Ast.Html.Block.AnnotatedBlockTest do
     test "even non-closed block elements" do
       markdown = "<div>\n```elixir\ndefmodule Mine do\n</div>"
       ast = [vtag("div", ["```elixir", "defmodule Mine do"])]
-      messages = []
+      messages = [{:warning, 1, "Failed to find closing <div>"}]
 
-      assert as_ast(markdown, annotations: @annotations) == {:ok, ast, messages}
+      assert as_ast(markdown, annotations: @annotations) == {:error, ast, messages}
```
Comment (josevalim) [inline test/acceptance/ast/html/block/annotated_block_test.exs:80]: It is the same AST but note the AST already differs from GitHub. So I am fine with emitting a warning to try to force users to fix up their markdown.

Comment (RobertDober) [reply test/acceptance/ast/html/block/annotated_block_test.exs:80]: ok with me

File: test/acceptance/ast/fenced_code_blocks_test.exs [hunk 2]
```diff
@@ -69,18 +69,41 @@
...
 
     test "in list" do
-      markdown = "- a\n- ```\n  b\n\n\n ```\n- c\n"
+      markdown = "- a\n- ```\n  b\n\n\n ```\n c\n- d\n"
       ast = [{ "ul", [],
         [{"li", [], ["a"], %{}},
-         {"li", [], [{"pre", [], [{"code", [], ["  b\n\n"], %{}}], %{}}], %{}},
-         {"li", [], ["c"], %{}}
+         {"li", [], [{"pre", [], [{"code", [], ["  b\n\n"], %{}}], %{}}, "c"], %{}},
+         {"li", [], ["d"], %{}}
```
Comment (josevalim) [inline test/acceptance/ast/fenced_code_blocks_test.exs:76]: This is improving the coverage to consider list items after the code block.

**Comment by josevalim** [comment]
Hi @RobertDober, when you have a second, can you release a new version with this fix? Either v1.5.0 or v1.4.19 works for us. :) Thank you! :heart:

**Comment by RobertDober** [comment]
I'll try to do it tonight...

**Comment by RobertDober** [comment]
DONE https://hex.pm/packages/earmark_parser

**Comment by RobertDober** [comment]
@josevalim 
I appologize but I released too old a version.

New job and master branch dirty because I caught a bug just before releasing 1.5.0  😓 

As they say, when it rains it pours

I'll release 1.4.20 ASAP

**Comment by RobertDober** [comment]
@josevalim never mind all is ok, sorry

**Comment by josevalim** [comment]
Yeah, i tested it and it worked great :)
